<pre>
<center>
<font face='Fira Code'><div style='background-color:#282C34;line-height:12pt'>
<span style="background-color:#282C34"><font color="#56B6C2">◉ Installation</font></span><span style="background-color:#282C34"><font color="#ABB2BF">                                                                                      </font></span>
<span style="background-color:#282C34"><font color="#E86671"> ◎ Dump this into your terminal</font></span><span style="background-color:#282C34"><font color="#ABB2BF">                                                                     </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">@code</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> </font></span><span style="background-color:#22252C"><font color="#E5C07B">sh</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                         </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#ABB2BF">git clone https://github.com/viperx7/norg2html                                                   </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">cd</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> norg2html                                                                                     </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#ABB2BF">pip3 install </font></span><span style="background-color:#22252C"><font color="#E86671">-r</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> requirements.txt                                                                 </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">mv</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> norg2html.py ~/.local/bin/norg2html                                                           </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#ABB2BF">chomd </font></span><span style="background-color:#22252C"><font color="#E86671">+x</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> ~/.local/bin/norg2html                                                                  </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">cd</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> ..                                                                                            </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">rm</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> norg2html </font></span><span style="background-color:#22252C"><font color="#E86671">-r</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                  </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">@end</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                             </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">                                                                                                    </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">                                                                                                    </font></span>
<span style="background-color:#282C34"><font color="#E86671"> ◎ Requirements</font></span><span style="background-color:#282C34"><font color="#ABB2BF">                                                                                     </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#282C34"><font color="#C678DD">⒈ </font></span><span style="background-color:#282C34"><font color="#5C6370"><b>*</b></font></span><span style="background-color:#282C34"><font color="#ABB2BF"><b>Gnome Terminal</b></font></span><span style="background-color:#282C34"><font color="#5C6370"><b>*</b></font></span><span style="background-color:#282C34"><font color="#ABB2BF">  : </font></span><span style="background-color:#282C34"><font color="#5C6370"><i>/</i></font></span><span style="background-color:#282C34"><font color="#ABB2BF"><i>No other terminal would work</i></font></span><span style="background-color:#282C34"><font color="#5C6370"><i>/</i></font></span><span style="background-color:#282C34"><font color="#ABB2BF">                                             </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#282C34"><font color="#C678DD">⒉ </font></span><span style="background-color:#282C34"><font color="#5C6370"><b>*</b></font></span><span style="background-color:#282C34"><font color="#ABB2BF"><b>stty</b></font></span><span style="background-color:#282C34"><font color="#5C6370"><b>*</b></font></span><span style="background-color:#282C34"><font color="#ABB2BF">            : </font></span><span style="background-color:#282C34"><font color="#5C6370"><i>/</i></font></span><span style="background-color:#282C34"><font color="#ABB2BF"><i>This should be already there</i></font></span><span style="background-color:#282C34"><font color="#5C6370"><i>/</i></font></span><span style="background-color:#282C34"><font color="#ABB2BF">                                             </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">                                                                                                    </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">                                                                                                    </font></span>
<span style="background-color:#282C34"><font color="#56B6C2">◉ Usage</font></span><span style="background-color:#282C34"><font color="#ABB2BF">                                                                                             </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#C678DD">@code</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> </font></span><span style="background-color:#22252C"><font color="#E5C07B">term</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                        </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">usage: norg2html [-h] [--output OUTPUT] [--font FONT] [--bgcolor BGCOLOR]                         </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">                    [--colorscheme COLORSCHEME] [--width WIDTH] [--presenter]                     </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">                    path                                                                          </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                                  </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">positional arguments:                                                                             </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  path                                                                                            </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                                  </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">options:                                                                                          </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  -h, --help                 show this help message and exit                                      </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  --output OUTPUT            path to output                                                       </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  --font FONT                font to set for the output                                           </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  --bgcolor BGCOLOR          background color to fill                                             </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  --colorscheme COLORSCHEME  specify vim colorscheme                                              </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  --width WIDTH              specify width                                                        </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  --presenter                Enable norg presenter mode&lt;/pre&gt;                                     </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#ABB2BF">  </font></span><span style="background-color:#22252C"><font color="#C678DD">@end</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                            </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">                                                                                                    </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">                                                                                                    </font></span>
<span style="background-color:#282C34"><font color="#E86671"> ◎ This document is generated by the following command</font></span><span style="background-color:#282C34"><font color="#ABB2BF">                                              </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">                                                                                                    </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">@code</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> </font></span><span style="background-color:#22252C"><font color="#E5C07B">sh</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                         </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#ABB2BF">norg2html ./README.norg </font></span><span style="background-color:#22252C"><font color="#E86671">--width</font></span><span style="background-color:#22252C"><font color="#ABB2BF"> </font></span><span style="background-color:#22252C"><font color="#D19A66">100</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                              </font></span>
<span style="background-color:#282C34"><font color="#ABB2BF">   </font></span><span style="background-color:#22252C"><font color="#C678DD">@end</font></span><span style="background-color:#22252C"><font color="#ABB2BF">                                                                                             </font></span>
<span style="background-color:#282C34"><font color="#282C34">~                                                                                                   </font></span>
<span style="background-color:#282C34"><font color="#282C34">~                                                                                                   </font></span>
<span style="background-color:#282C34"><font color="#282C34">~                                                                                                   </font></span>
</div>
</font>
</center>
</pre>